var myApp = angular.module('myApp', []);

myApp.controller('MyController', function MyController($scope) {
	$scope.players = [
	{
	    "firstname":"Brandon",
	    "lastname":"Belt",
	    "position":"infielder",
	    "role":"none",
	    "bats":"Left",
        "throws":"Left"
    },
	{
	    "firstname":"Brandon",
	    "lastname":"Crawford",
	    "position":"infielder",
	    "role":"none",
	    "bats":"Left",
        "throws":"Right"
    },
	{
	    "firstname":"Buster",
	    "lastname":"Posey",
	    "position":"catcher",
	    "role":"none",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Denard",
	    "lastname":"Span",
	    "position":"outfielder",
	    "role":"none",
	    "bats":"Left",
        "throws":"Left"
    },
    {
	    "firstname":"Derek",
	    "lastname":"Law",
	    "position":"pitcher",
	    "role":"reliever",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Eduardo",
	    "lastname":"Nunez",
	    "position":"infielder",
	    "role":"none",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"George",
	    "lastname":"Kontos",
	    "position":"pitcher",
	    "role":"reliever",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Hunter",
	    "lastname":"Pence",
	    "position":"outfielder",
	    "role":"none",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Hunter",
	    "lastname":"Strickland",
	    "position":"pitcher",
	    "role":"reliever",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Jeff",
	    "lastname":"Samardzija",
	    "position":"pitcher",
	    "role":"starter",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Joe",
	    "lastname":"Panik",
	    "position":"infielder",
	    "role":"none",
	    "bats":"Left",
        "throws":"Right"
    },
    {
	    "firstname":"Madison",
	    "lastname":"Bumgarner",
	    "position":"pitcher",
	    "role":"starter",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Johnny",
	    "lastname":"Cueto",
	    "position":"pitcher",
	    "role":"starter",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Matt",
	    "lastname":"Cain",
	    "position":"pitcher",
	    "role":"starter",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Matt",
	    "lastname":"Moore",
	    "position":"pitcher",
	    "role":"starter",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Mark",
	    "lastname":"Melancon",
	    "position":"pitcher",
	    "role":"reliever",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Jarrett",
	    "lastname":"Parker",
	    "position":"outfielder",
	    "role":"none",
	    "bats":"Right",
        "throws":"Right"
    },
    {
	    "firstname":"Mac",
	    "lastname":"Williamson",
	    "position":"outfielder",
	    "role":"none",
	    "bats":"Right",
        "throws":"Right"
    }
]
});